#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

TARGET_LINUX_KERNEL_VERSION := 5.4

TARGET_SOC_BASE := exynos2100

# UNIVERSAL common modules
BOARD_USES_EXYNOS_GRALLOC_VERSION := 4
BOARD_USES_ALIGN_RESTRICTION := true
BOARD_USES_GRALLOC_ION_SYNC := true

# Acryl
BOARD_LIBACRYL_DEFAULT_COMPOSITOR := no_default_compositor
BOARD_LIBACRYL_DEFAULT_SCALER := mscl_votf
BOARD_LIBACRYL_DEFAULT_BLTER := no_default_blter	

BOARD_LIBHDR_PLUGIN := libhdr_plugin_default
BOARD_LIBHDR10P_META_PLUGIN := libhdr10p_meta_plugin_default

# Codec2
BOARD_USE_CSC_FILTER := true
BOARD_USE_DEC_SW_CSC := false
BOARD_USE_ENC_SW_CSC := false
BOARD_SUPPORT_MFC_ENC_RGB := true
BOARD_USE_BLOB_ALLOCATOR := true
BOARD_USE_PERFORMANCE := true
BOARD_USE_QUERY_HDR2SDR := false
BOARD_USE_COMPRESSED_COLOR := true

# Gralloc4
BOARD_GPU_SUPPORT_AFBC_BASIC := true
BOARD_GRALLOC_DPU_SUPPORT_1010102_AFBC := true
BOARD_GRALLOC_INIT_AFBC := true

# Graphics
BOARD_USES_EXYNOS_DATASPACE_FEATURE := true

# HWComposer
BOARD_USES_HDR_INTERFACE := true
BOARD_USES_EXYNOS_AFBC_FEATURE := true

# OMX
BOARD_USE_DMA_BUF := true
BOARD_USE_NON_CACHED_GRAPHICBUFFER := true
BOARD_USE_GSC_RGB_ENCODER := true
BOARD_USE_CSC_HW := false
BOARD_USE_S3D_SUPPORT := false
BOARD_USE_DEINTERLACING_SUPPORT := true
BOARD_USE_HEVCENC_SUPPORT := true
BOARD_USE_HEVC_HWIP := false
BOARD_USE_VP9DEC_SUPPORT := true
BOARD_USE_VP9ENC_SUPPORT := true
BOARD_USE_WFDENC_SUPPORT := true
BOARD_USE_CUSTOM_COMPONENT_SUPPORT := true
BOARD_USE_VIDEO_EXT_FOR_WFD_HDCP := true
BOARD_USE_SINGLE_PLANE_IN_DRM := false
BOARD_USE_WA_ION_BUF_REF := true
BOARD_USE_DIVX_ENABLE := true

# WifiDisplay
BOARD_USES_VIRTUAL_DISPLAY := true
BOARD_USES_DISABLE_COMPOSITIONTYPE_GLES := true
BOARD_USES_SECURE_ENCODER_ONLY := true

# Scaler
BOARD_DEFAULT_CSC_HW_SCALER := 4
BOARD_USES_SCALER_M2M1SHOT := true

# H/W align restriction of MM IPs
BOARD_EXYNOS_S10B_FORMAT_ALIGN := 64

# Libhwjpeg
$(call soong_config_set,libhwjpeg,HWJPEG_ANDROID_VERSION,11)

include hardware/samsung_slsi-linaro/config/BoardConfigCommon.mk
