#
# SPDX-FileCopyrightText: The LineageOS Project
# SPDX-License-Identifier: Apache-2.0
#

TARGET_LINUX_KERNEL_VERSION := 5.15

TARGET_SOC_BASE := s5e8535

# Gralloc
BOARD_USES_EXYNOS_GRALLOC_VERSION := 4
BOARD_EXYNOS_S10B_FORMAT_ALIGN := 64
BOARD_GRALLOC_NO_EXTERNAL_AFBC := true
BOARD_GRALLOC_INIT_AFBC := true
BOARD_USES_GRALLOC_ION_SYNC := true
BOARD_USES_MFC_CHROMA_VALIGN := true

# Codec2
BOARD_USE_CSC_FILTER := true
BOARD_USE_DMA_BUF := true
BOARD_USE_NON_CACHED_GRAPHICBUFFER := true
BOARD_USE_GSC_RGB_ENCODER := true
BOARD_USE_CSC_HW := false
BOARD_USE_S3D_SUPPORT := false
BOARD_USE_DEINTERLACING_SUPPORT := true
BOARD_USE_HEVCENC_SUPPORT := true
BOARD_USE_HEVC_HWIP := false
BOARD_USE_SINGLE_PLANE_IN_DRM := true
BOARD_USE_WA_ION_BUF_REF := true

# HWC
BOARD_USES_HWC_SERVICES := false

# SCALER
BOARD_DEFAULT_CSC_HW_SCALER := 4
BOARD_USES_SCALER_M2M1SHOT := true
BOARD_HAS_SCALER_ALIGN_RESTRICTION := true

# Acryl
BOARD_LIBACRYL_DEFAULT_COMPOSITOR := no_default_compositor
BOARD_LIBACRYL_DEFAULT_SCALER := mscl_9810
BOARD_LIBACRYL_DEFAULT_BLTER := no_default_blter

include hardware/samsung_slsi-linaro/config/BoardConfigCommon.mk
